### ISSUE TITLE
xah-elisp-mode: Symbol's value as variable is void: ac-modes

### ISSUE THREAD

**Issue by LevskiWeng** [xahlee/xah-elisp-mode#3]
**Version**
xah-elisp-mode-20150610.1756

**Emacs version**
24.3.1

When I opened a file `xxx.el` and executed `M-x xah-elisp-mode`, the syntax highlight seemed to work, but the emacs said:

    xah-elisp-mode: Symbol's value as variable is void: ac-modes

I'm an Emacs newbie, could you help me to solve the problem?

Thanks.

**Comment by xahlee** [comment]
that's setup for another mode, the auto-complete mode. Should be of no concern.

**Comment by xahlee** [comment]
i made changes to the code. Should be fixed. Thanks.
