### ISSUE TITLE
Identation for property lists

### ISSUE THREAD

**Issue by brabalan** [xahlee/xah-elisp-mode#5]
I find the indentation strange for property lists:
``` emacs-lisp
       (org-element-headline-interpreter
        `(headline (:level 1
                           :title ,name
                           :tags ("game")))
```
Is there a reason why they are not aligned?

**Comment by xahlee** [comment]
yeah. Though emacs-lisp-mode does that too.
Right now xah-elisp-mode is just using emacs-lisp-mode's indentation scheme.
Fixing this will need writing a parser... would be major undertaking.

**Comment by brabalan** [comment]
Ah, sorry, I thought you were doing something special for indentation.
