### ISSUE TITLE
Symbol's value as variable is void: ido-decorations

### ISSUE THREAD

**Issue by jdhao** [xahlee/xah-elisp-mode#9]
After installing this package, when I run comand `xah-elisp-mode`, I got the following error:

> Symbol's value as variable is void: ido-decorations

Emacs version: 27.2
system: macOS catalina

**Comment by xahlee** [comment]
added require ido in latest commit. thanks. close issue if it's good. thanks.

**Comment by jdhao** [comment]
Thanks, it fixes the issue for me.
